services:
  api-send:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - MY_EMAIL=${MY_EMAIL}
    env_file:
      - .env
   # volumes:
   #   - .:/home/app
   #   - /home/app/node_modules
